import Foundation

/// Data tables copied from stardew-checkup.js.
enum CollectionData {
    static let cookingRecipes: [(String, String)] = [
        ("194", "Fried Egg"),
        ("195", "Omelet"),
        ("196", "Salad"),
        ("197", "Cheese Cauliflower"),
        ("198", "Baked Fish"),
        ("199", "Parsnip Soup"),
        ("200", "Vegetable Medley"),
        ("201", "Complete Breakfast"),
        ("202", "Fried Calamari"),
        ("203", "Strange Bun"),
        ("204", "Lucky Lunch"),
        ("205", "Fried Mushroom"),
        ("206", "Pizza"),
        ("207", "Bean Hotpot"),
        ("208", "Glazed Yams"),
        ("209", "Carp Surprise"),
        ("210", "Hashbrowns"),
        ("211", "Pancakes"),
        ("212", "Salmon Dinner"),
        ("213", "Fish Taco"),
        ("214", "Crispy Bass"),
        ("215", "Pepper Poppers"),
        ("216", "Bread"),
        ("218", "Tom Kha Soup"),
        ("219", "Trout Soup"),
        ("220", "Chocolate Cake"),
        ("221", "Pink Cake"),
        ("222", "Rhubarb Pie"),
        ("223", "Cookie"),
        ("224", "Spaghetti"),
        ("225", "Fried Eel"),
        ("226", "Spicy Eel"),
        ("227", "Sashimi"),
        ("228", "Maki Roll"),
        ("229", "Tortilla"),
        ("230", "Red Plate"),
        ("231", "Eggplant Parmesan"),
        ("232", "Rice Pudding"),
        ("233", "Ice Cream"),
        ("234", "Blueberry Tart"),
        ("235", "Autumn's Bounty"),
        ("236", "Pumpkin Soup"),
        ("237", "Super Meal"),
        ("238", "Cranberry Sauce"),
        ("239", "Stuffing"),
        ("240", "Farmer's Lunch"),
        ("241", "Survival Burger"),
        ("242", "Dish O' The Sea"),
        ("243", "Miner's Treat"),
        ("244", "Roots Platter"),
        ("456", "Algae Soup"),
        ("457", "Pale Broth"),
        ("604", "Plum Pudding"),
        ("605", "Artichoke Dip"),
        ("606", "Stir Fry"),
        ("607", "Roasted Hazelnuts"),
        ("608", "Pumpkin Pie"),
        ("609", "Radish Salad"),
        ("610", "Fruit Salad"),
        ("611", "Blackberry Cobbler"),
        ("612", "Cranberry Candy"),
        ("618", "Bruschetta"),
        ("648", "Coleslaw"),
        ("649", "Fiddlehead Risotto"),
        ("651", "Poppyseed Muffin"),
        ("727", "Chowder"),
        ("728", "Fish Stew"),
        ("729", "Escargot"),
        ("730", "Lobster Bisque"),
        ("731", "Maple Bar"),
        ("732", "Crab Cakes"),
    ]

    static let craftingRecipes: [String] = [
        "Cherry Bomb",
        "Bomb",
        "Mega Bomb",
        "Gate",
        "Wood Fence",
        "Stone Fence",
        "Iron Fence",
        "Hardwood Fence",
        "Sprinkler",
        "Quality Sprinkler",
        "Iridium Sprinkler",
        "Mayonnaise Machine",
        "Bee House",
        "Preserves Jar",
        "Cheese Press",
        "Loom",
        "Keg",
        "Oil Maker",
        "Cask",
        "Basic Fertilizer",
        "Quality Fertilizer",
        "Speed-Gro",
        "Deluxe Speed-Gro",
        "Basic Retaining Soil",
        "Quality Retaining Soil",
        "Wild Seeds (Sp)",
        "Wild Seeds (Su)",
        "Wild Seeds (Fa)",
        "Wild Seeds (Wi)",
        "Ancient Seeds",
        "Wood Floor",
        "Straw Floor",
        "Weathered Floor",
        "Crystal Floor",
        "Stone Floor",
        "Wood Path",
        "Gravel Path",
        "Cobblestone Path",
        "Stepping Stone Path",
        "Crystal Path",
        "Spinner",
        "Trap Bobber",
        "Cork Bobber",
        "Treasure Hunter",
        "Dressed Spinner",
        "Barbed Hook",
        "Magnet",
        "Bait",
        "Wild Bait",
        "Crab Pot",
        "Sturdy Ring",
        "Warrior Ring",
        "Ring of Yoba",
        "Iridium Band",
        "Field Snack",
        "Life Elixir",
        "Oil of Garlic",
        "Torch",
        "Campfire",
        "Wooden Brazier",
        "Stone Brazier",
        "Gold Brazier",
        "Carved Brazier",
        "Stump Brazier",
        "Barrel Brazier",
        "Skull Brazier",
        "Marble Brazier",
        "Wood Lamp-post",
        "Iron Lamp-post",
        "Jack-O-Lantern",
        "Chest",
        "Furnace",
        "Scarecrow",
        "Seed Maker",
        "Staircase",
        "Explosive Ammo",
        "Transmute (Fe)",
        "Transmute (Au)",
        "Crystalarium",
        "Charcoal Kiln",
        "Lightning Rod",
        "Recycling Machine",
        "Tapper",
        "Worm Bin",
        "Slime Egg-Press",
        "Slime Incubator",
        "Warp Totem: Beach",
        "Warp Totem: Mountains",
        "Warp Totem: Farm",
        "Rain Totem",
        "Tub o' Flowers",
        "Wicked Statue",
        "Flute Block",
        "Drum Block",
    ]

    static let fish: [(String, String)] = [
        ("152", "Seaweed"),
        ("153", "Green Algae"),
        ("157", "White Algae"),
        ("128", "Pufferfish"),
        ("129", "Anchovy"),
        ("130", "Tuna"),
        ("131", "Sardine"),
        ("132", "Bream"),
        ("136", "Largemouth Bass"),
        ("137", "Smallmouth Bass"),
        ("138", "Rainbow Trout"),
        ("139", "Salmon"),
        ("140", "Walleye"),
        ("141", "Perch"),
        ("142", "Carp"),
        ("143", "Catfish"),
        ("144", "Pike"),
        ("145", "Sunfish"),
        ("146", "Red Mullet"),
        ("147", "Herring"),
        ("148", "Eel"),
        ("149", "Octopus"),
        ("150", "Red Snapper"),
        ("151", "Squid"),
        ("154", "Sea Cucumber"),
        ("155", "Super Cucumber"),
        ("156", "Ghostfish"),
        ("158", "Stonefish"),
        ("159", "Crimsonfish"),
        ("160", "Angler"),
        ("161", "Ice Pip"),
        ("162", "Lava Eel"),
        ("163", "Legend"),
        ("164", "Sandfish"),
        ("165", "Scorpion Carp"),
        ("682", "Mutant Carp"),
        ("698", "Sturgeon"),
        ("699", "Tiger Trout"),
        ("700", "Bullhead"),
        ("701", "Tilapia"),
        ("702", "Chub"),
        ("704", "Dorado"),
        ("705", "Albacore"),
        ("706", "Shad"),
        ("707", "Lingcod"),
        ("708", "Halibut"),
        ("715", "Lobster"),
        ("716", "Crayfish"),
        ("717", "Crab"),
        ("718", "Cockle"),
        ("719", "Mussel"),
        ("720", "Shrimp"),
        ("721", "Snail"),
        ("722", "Periwinkle"),
        ("723", "Oyster"),
        ("734", "Woodskip"),
        ("775", "Glacierfish"),
        ("795", "Void Salmon"),
        ("796", "Slimejack"),
    ]

    static let fishIgnore: Set<String> = ["308", "79", "797", "191", "103", "73", "842", "821", "825", "890", "388", "390", "2332", "2334", "2396", "2418", "2419", "2421", "2423", "2425", "2427", "2732", "2814", "393", "78"]

    static let basicShipping: [(String, String)] = [
        ("16", "Wild Horseradish"),
        ("18", "Daffodil"),
        ("20", "Leek"),
        ("22", "Dandelion"),
        ("24", "Parsnip"),
        ("78", "Cave Carrot"),
        ("88", "Coconut"),
        ("90", "Cactus Fruit"),
        ("92", "Sap"),
        ("174", "Large Egg (White)"),
        ("176", "Egg (White)"),
        ("180", "Egg (Brown)"),
        ("182", "Large Egg (Brown)"),
        ("184", "Milk"),
        ("186", "Large Milk"),
        ("188", "Green Bean"),
        ("190", "Cauliflower"),
        ("192", "Potato"),
        ("248", "Garlic"),
        ("250", "Kale"),
        ("252", "Rhubarb"),
        ("254", "Melon"),
        ("256", "Tomato"),
        ("257", "Morel"),
        ("258", "Blueberry"),
        ("259", "Fiddlehead Fern"),
        ("260", "Hot Pepper"),
        ("262", "Wheat"),
        ("264", "Radish"),
        ("266", "Red Cabbage"),
        ("268", "Starfruit"),
        ("270", "Corn"),
        ("272", "Eggplant"),
        ("274", "Artichoke"),
        ("276", "Pumpkin"),
        ("278", "Bok Choy"),
        ("280", "Yam"),
        ("281", "Chanterelle"),
        ("282", "Cranberries"),
        ("283", "Holly"),
        ("284", "Beet"),
        ("296", "Salmonberry"),
        ("300", "Amaranth"),
        ("303", "Pale Ale"),
        ("304", "Hops"),
        ("305", "Void Egg"),
        ("306", "Mayonnaise"),
        ("307", "Duck Mayonnaise"),
        ("308", "Void Mayonnaise"),
        ("330", "Clay"),
        ("334", "Copper Bar"),
        ("335", "Iron Bar"),
        ("336", "Gold Bar"),
        ("337", "Iridium Bar"),
        ("338", "Refined Quartz"),
        ("340", "Honey"),
        ("342", "Pickles"),
        ("344", "Jelly"),
        ("346", "Beer"),
        ("348", "Wine"),
        ("350", "Juice"),
        ("372", "Clam"),
        ("376", "Poppy"),
        ("378", "Copper Ore"),
        ("380", "Iron Ore"),
        ("382", "Coal"),
        ("384", "Gold Ore"),
        ("386", "Iridium Ore"),
        ("388", "Wood"),
        ("390", "Stone"),
        ("392", "Nautilus Shell"),
        ("393", "Coral"),
        ("394", "Rainbow Shell"),
        ("396", "Spice Berry"),
        ("397", "Sea Urchin"),
        ("398", "Grape"),
        ("399", "Spring Onion"),
        ("400", "Strawberry"),
        ("402", "Sweet Pea"),
        ("404", "Common Mushroom"),
        ("406", "Wild Plum"),
        ("408", "Hazelnut"),
        ("410", "Blackberry"),
        ("412", "Winter Root"),
        ("414", "Crystal Fruit"),
        ("416", "Snow Yam"),
        ("417", "Sweet Gem Berry"),
        ("418", "Crocus"),
        ("420", "Red Mushroom"),
        ("421", "Sunflower"),
        ("422", "Purple Mushroom"),
        ("424", "Cheese"),
        ("426", "Goat Cheese"),
        ("428", "Cloth"),
        ("430", "Truffle"),
        ("432", "Truffle Oil"),
        ("433", "Coffee Bean"),
        ("436", "Goat Milk"),
        ("438", "Large Goat Milk"),
        ("440", "Wool"),
        ("442", "Duck Egg"),
        ("444", "Duck Feather"),
        ("446", "Rabbit's Foot"),
        ("454", "Ancient Fruit"),
        ("459", "Mead"),
        ("591", "Tulip"),
        ("593", "Summer Spangle"),
        ("595", "Fairy Rose"),
        ("597", "Blue Jazz"),
        ("613", "Apple"),
        ("634", "Apricot"),
        ("635", "Orange"),
        ("636", "Peach"),
        ("637", "Pomegranate"),
        ("638", "Cherry"),
        ("684", "Bug Meat"),
        ("709", "Hardwood"),
        ("724", "Maple Syrup"),
        ("725", "Oak Resin"),
        ("726", "Pine Tar"),
        ("766", "Slime"),
        ("767", "Bat Wing"),
        ("768", "Solar Essence"),
        ("769", "Void Essence"),
        ("771", "Fiber"),
        ("787", "Battery Pack"),
    ]

    static let polyCrops: [(String, String)] = [
        ("24", "Parsnip"),
        ("188", "Green Bean"),
        ("190", "Cauliflower"),
        ("192", "Potato"),
        ("248", "Garlic"),
        ("250", "Kale"),
        ("256", "Tomato"),
        ("262", "Wheat"),
        ("264", "Radish"),
        ("266", "Red Cabbage"),
        ("270", "Corn"),
        ("272", "Eggplant"),
        ("274", "Artichoke"),
        ("276", "Pumpkin"),
        ("278", "Bok Choy"),
        ("280", "Yam"),
        ("284", "Beet"),
        ("300", "Amaranth"),
        ("304", "Hops"),
        ("252", "Rhubarb"),
        ("254", "Melon"),
        ("258", "Blueberry"),
        ("260", "Hot Pepper"),
        ("268", "Starfruit"),
        ("282", "Cranberries"),
        ("398", "Grape"),
        ("400", "Strawberry"),
        ("433", "Coffee Bean"),
    ]

    static let artifacts: [(String, String)] = [
        ("96", "Dwarf Scroll I"),
        ("97", "Dwarf Scroll II"),
        ("98", "Dwarf Scroll III"),
        ("99", "Dwarf Scroll IV"),
        ("100", "Chipped Amphora"),
        ("101", "Arrowhead"),
        ("103", "Ancient Doll"),
        ("104", "Elvish Jewelry"),
        ("105", "Chewing Stick"),
        ("106", "Ornamental Fan"),
        ("107", "Dinosaur Egg"),
        ("108", "Rare Disc"),
        ("109", "Ancient Sword"),
        ("110", "Rusty Spoon"),
        ("111", "Rusty Spur"),
        ("112", "Rusty Cog"),
        ("113", "Chicken Statue"),
        ("114", "Ancient Seed"),
        ("115", "Prehistoric Tool"),
        ("116", "Dried Starfish"),
        ("117", "Anchor"),
        ("118", "Glass Shards"),
        ("119", "Bone Flute"),
        ("120", "Prehistoric Handaxe"),
        ("121", "Dwarvish Helm"),
        ("122", "Dwarf Gadget"),
        ("123", "Ancient Drum"),
        ("124", "Golden Mask"),
        ("125", "Golden Relic"),
        ("126", "Strange Doll (green)"),
        ("127", "Strange Doll (yellow)"),
        ("579", "Prehistoric Scapula"),
        ("580", "Prehistoric Tibia"),
        ("581", "Prehistoric Skull"),
        ("582", "Skeletal Hand"),
        ("583", "Prehistoric Rib"),
        ("584", "Prehistoric Vertebra"),
        ("585", "Skeletal Tail"),
        ("586", "Nautilus Fossil"),
        ("587", "Amphibian Fossil"),
        ("588", "Palm Fossil"),
        ("589", "Trilobite"),
    ]

    static let minerals: [(String, String)] = [
        ("60", "Emerald"),
        ("62", "Aquamarine"),
        ("64", "Ruby"),
        ("66", "Amethyst"),
        ("68", "Topaz"),
        ("70", "Jade"),
        ("72", "Diamond"),
        ("74", "Prismatic Shard"),
        ("80", "Quartz"),
        ("82", "Fire Quartz"),
        ("84", "Frozen Tear"),
        ("86", "Earth Crystal"),
        ("538", "Alamite"),
        ("539", "Bixite"),
        ("540", "Baryte"),
        ("541", "Aerinite"),
        ("542", "Calcite"),
        ("543", "Dolomite"),
        ("544", "Esperite"),
        ("545", "Fluorapatite"),
        ("546", "Geminite"),
        ("547", "Helvite"),
        ("548", "Jamborite"),
        ("549", "Jagoite"),
        ("550", "Kyanite"),
        ("551", "Lunarite"),
        ("552", "Malachite"),
        ("553", "Neptunite"),
        ("554", "Lemon Stone"),
        ("555", "Nekoite"),
        ("556", "Orpiment"),
        ("557", "Petrified Slime"),
        ("558", "Thunder Egg"),
        ("559", "Pyrite"),
        ("560", "Ocean Stone"),
        ("561", "Ghost Crystal"),
        ("562", "Tigerseye"),
        ("563", "Jasper"),
        ("564", "Opal"),
        ("565", "Fire Opal"),
        ("566", "Celestine"),
        ("567", "Marble"),
        ("568", "Sandstone"),
        ("569", "Granite"),
        ("570", "Basalt"),
        ("571", "Limestone"),
        ("572", "Soapstone"),
        ("573", "Hematite"),
        ("574", "Mudstone"),
        ("575", "Obsidian"),
        ("576", "Slate"),
        ("577", "Fairy Stone"),
        ("578", "Star Shards"),
    ]

    static let defaultBundleData: [(String, String)] = [
        ("Pantry/0", "Spring Crops/O 465 20/24 1 0 188 1 0 190 1 0 192 1 0/0///Spring Crops"),
        ("Pantry/1", "Summer Crops/O 621 1/256 1 0 260 1 0 258 1 0 254 1 0/3///Summer Crops"),
        ("Pantry/2", "Fall Crops/BO 10 1/270 1 0 272 1 0 276 1 0 280 1 0/2///Fall Crops"),
        ("Pantry/3", "Quality Crops/BO 15 1/24 5 2 254 5 2 276 5 2 270 5 2/6/3//Quality Crops"),
        ("Pantry/4", "Animal/BO 16 1/186 1 0 182 1 0 174 1 0 438 1 0 440 1 0 442 1 0/4/5//Animal"),
        ("Pantry/5", "Artisan/BO 12 1/432 1 0 428 1 0 426 1 0 424 1 0 340 1 0 344 1 0 613 1 0 634 1 0 635 1 0 636 1 0 637 1 0 638 1 0/1/6//Artisan"),
        ("Crafts Room/13", "Spring Foraging/O 495 30/16 1 0 18 1 0 20 1 0 22 1 0/0///Spring Foraging"),
        ("Crafts Room/14", "Summer Foraging/O 496 30/396 1 0 398 1 0 402 1 0/3///Summer Foraging"),
        ("Crafts Room/15", "Fall Foraging/O 497 30/404 1 0 406 1 0 408 1 0 410 1 0/2///Fall Foraging"),
        ("Crafts Room/16", "Winter Foraging/O 498 30/412 1 0 414 1 0 416 1 0 418 1 0/6///Winter Foraging"),
        ("Crafts Room/17", "Construction/BO 114 1/388 99 0 388 99 0 390 99 0 709 10 0/4///Construction"),
        ("Crafts Room/19", "Exotic Foraging/O 235 5/88 1 0 90 1 0 78 1 0 420 1 0 422 1 0 724 1 0 725 1 0 726 1 0 257 1 0/1/5//Exotic Foraging"),
        ("Fish Tank/6", "River Fish/O 685 30/145 1 0 143 1 0 706 1 0 699 1 0/6///River Fish"),
        ("Fish Tank/7", "Lake Fish/O 687 1/136 1 0 142 1 0 700 1 0 698 1 0/0///Lake Fish"),
        ("Fish Tank/8", "Ocean Fish/O 690 5/131 1 0 130 1 0 150 1 0 701 1 0/5///Ocean Fish"),
        ("Fish Tank/9", "Night Fishing/R 516 1/140 1 0 132 1 0 148 1 0/1///Night Fishing"),
        ("Fish Tank/10", "Specialty Fish/O 242 5/128 1 0 156 1 0 164 1 0 734 1 0/4///Specialty Fish"),
        ("Fish Tank/11", "Crab Pot/O 710 3/715 1 0 716 1 0 717 1 0 718 1 0 719 1 0 720 1 0 721 1 0 722 1 0 723 1 0 372 1 0/1/5//Crab Pot"),
        ("Boiler Room/20", "Blacksmith's/BO 13 1/334 1 0 335 1 0 336 1 0/2///Blacksmith's"),
        ("Boiler Room/21", "Geologist's/O 749 5/80 1 0 86 1 0 84 1 0 82 1 0/1///Geologist's"),
        ("Boiler Room/22", "Adventurer's/R 518 1/766 99 0 767 10 0 768 1 0 769 1 0/1/2//Adventurer's"),
        ("Vault/23", "2,500g/O 220 3/-1 2500 2500/4///2,500g"),
        ("Vault/24", "5,000g/O 369 30/-1 5000 5000/2///5,000g"),
        ("Vault/25", "10,000g/BO 9 1/-1 10000 10000/3///10,000g"),
        ("Vault/26", "25,000g/BO 21 1/-1 25000 25000/1///25,000g"),
        ("Bulletin Board/31", "Chef's/O 221 3/724 1 0 259 1 0 430 1 0 376 1 0 228 1 0 194 1 0/4///Chef's"),
        ("Bulletin Board/32", "Field Research/BO 20 1/422 1 0 392 1 0 702 1 0 536 1 0/5///Field Research"),
        ("Bulletin Board/33", "Enchanter's/O 336 5/725 1 0 348 1 0 446 1 0 637 1 0/1///Enchanter's"),
        ("Bulletin Board/34", "Dye/BO 25 1/420 1 0 397 1 0 421 1 0 444 1 0 62 1 0 266 1 0/6///Dye"),
        ("Bulletin Board/35", "Fodder/BO 104 1/262 10 0 178 10 0 613 3 0/3///Fodder"),
        ("Abandoned Joja Mart/36", "The Missing//348 1 1 807 1 0 74 1 0 454 5 2 795 1 2 445 1 0/1/5//The Missing"),
    ]

}

struct WalnutGoal {
    let id: String
    let num: Int
    let name: String
    let hint: String
}

enum WalnutData {
    static let allAtOnce: [WalnutGoal] = [
        WalnutGoal(id: "Bush_IslandEast_17_37", num: 1, name: "Island Jungle Bush", hint: "In open center area (17,37)"),
        WalnutGoal(id: "Bush_IslandShrine_23_34", num: 1, name: "Island Jungle Shrine Bush", hint: "Along Southern edge (23,34)"),
        WalnutGoal(id: "Bush_IslandSouth_31_5", num: 1, name: "Island South Bush", hint: "Accessed from hidden path East of stairs on Island North map (31,5)"),
        WalnutGoal(id: "Bush_IslandNorth_9_84", num: 1, name: "Island North Bush", hint: "Hidden clearing in trees West of stairs from dock area (9,84)"),
        WalnutGoal(id: "Bush_IslandNorth_20_26", num: 1, name: "Island North Bush", hint: "Hidden clearing in trees on West side in front of Volcano (20,26)"),
        WalnutGoal(id: "Bush_IslandNorth_56_27", num: 1, name: "Island North Bush", hint: "Behind coconut tree on East side in front of Volcano (56,27)"),
        WalnutGoal(id: "Bush_IslandNorth_4_42", num: 1, name: "Island North Bush", hint: "Grassy area above Dig Site (4,42)"),
        WalnutGoal(id: "Bush_IslandNorth_45_38", num: 1, name: "Island North Bush", hint: "Grassy area above Field Office (45,38)"),
        WalnutGoal(id: "Bush_IslandNorth_47_40", num: 1, name: "Island North Bush", hint: "Grassy area above Field Office (47,40)"),
        WalnutGoal(id: "Bush_IslandNorth_13_33", num: 1, name: "Island North Bush", hint: "Along river accessed via secret passage from Volcano entrance (13,33)"),
        WalnutGoal(id: "Bush_IslandNorth_5_30", num: 1, name: "Island North Bush", hint: "Along river accessed via secret passage from Volcano entrance (5,39)"),
        WalnutGoal(id: "Bush_Caldera_28_36", num: 1, name: "Volcano Caldera Bush", hint: "Along Southern edge (28,36)"),
        WalnutGoal(id: "Bush_Caldera_9_34", num: 1, name: "Volcano Caldera Bush", hint: "Along Southern edge (9,34)"),
        WalnutGoal(id: "Bush_CaptainRoom_2_4", num: 1, name: "Island West Shipwreck Bush", hint: "Shipwreck is enterable from left side (2,4)"),
        WalnutGoal(id: "TreeNut", num: 1, name: "Tree in Leo's Hut", hint: "Hit the tree with an axe"),
        WalnutGoal(id: "Buried_IslandNorth_19_39", num: 1, name: "Island North Buried", hint: "At top of stairs from Dig Site, marked by a circle of small rocks (19,39)"),
        WalnutGoal(id: "Buried_IslandNorth_19_13", num: 1, name: "Island North Buried", hint: "Cliff edge West of Volcano, marked by a circle of small rocks (19,13)"),
        WalnutGoal(id: "Buried_IslandNorth_57_79", num: 1, name: "Island North Buried", hint: "Sand patch within grass patch in SE corner, marked by a circle of small rocks (57,79)"),
        WalnutGoal(id: "Buried_IslandNorth_54_21", num: 1, name: "Island North Buried", hint: "Along Eastern edge of Volcano, between rocks and plants (54,21)"),
        WalnutGoal(id: "Buried_IslandNorth_42_77", num: 1, name: "Island North Buried", hint: "Dark grassy area just NE of stairs from dock, between tufts of long grass (42,77)"),
        WalnutGoal(id: "Buried_IslandNorth_62_54", num: 1, name: "Island North Buried", hint: "NE corner of path between docks and Field Office, marked by slightly raised sand (62,54)"),
        WalnutGoal(id: "Buried_IslandNorth_26_81", num: 1, name: "Island North Buried", hint: "Beneath curved tree West of stairs from dock, marked by a circle of small rocks (26,81)"),
        WalnutGoal(id: "IslandLeftPlantRestored", num: 1, name: "Field Office Plant Survey Reward", hint: "Correct count is 22 plants"),
        WalnutGoal(id: "IslandRightPlantRestored", num: 1, name: "Field Office Starfish Survey Reward", hint: "Correct count is 18 starfish"),
        WalnutGoal(id: "IslandBatRestored", num: 1, name: "Field Office Mummified Bat Reward", hint: "Found by breaking non-ore rocks in the Volcano"),
        WalnutGoal(id: "IslandFrogRestored", num: 1, name: "Field Office Mummified Frog Reward", hint: "Found by cutting weeds in Jungle"),
        WalnutGoal(id: "IslandCenterSkeletonRestored", num: 6, name: "Field Office Mammal Skeleton Reward", hint: "Skull -- Found in Golden Coconuts\nSpine -- Found by fishing in Island North\nLeg (2) -- Found by breaking fossil stones (high chance)\nRibs -- Found by breaking fossil stones (low chance)\nTail -- Found by panning in Island North"),
        WalnutGoal(id: "IslandSnakeRestored", num: 3, name: "Field Office Snake Skeleton Reward", hint: "Skull -- Found by digging artifact spots in Island North or West\n    and fishing in Island West\nVertebra (2) -- Found by digging artifact spots in Island West"),
        WalnutGoal(id: "Bush_IslandWest_104_3", num: 1, name: "Island West Bush", hint: "End of hidden path through dense trees in NE part of map (104,3)"),
        WalnutGoal(id: "Bush_IslandWest_31_24", num: 1, name: "Island West Bush", hint: "Behind Mahogany tree in Tiger Slime area (31,24)"),
        WalnutGoal(id: "Bush_IslandWest_38_56", num: 1, name: "Island West Bush", hint: "Behind palm tree near pond West of Birdie's hut (38,56)"),
        WalnutGoal(id: "Bush_IslandWest_75_29", num: 1, name: "Island West Bush", hint: "In front of the trees above farmhouse (75,29)"),
        WalnutGoal(id: "Bush_IslandWest_64_30", num: 1, name: "Island West Bush", hint: "Elevated area on West side of river; follow path counter-clockwise from Tiger Slimes (64,30)"),
        WalnutGoal(id: "Bush_IslandWest_54_18", num: 1, name: "Island West Bush", hint: "Obscured by dense trees along path between Tiger Slimes and suspension bridge (54,18)"),
        WalnutGoal(id: "Bush_IslandWest_25_30", num: 1, name: "Island West Bush", hint: "Along wall SE of walnut door (25,30)"),
        WalnutGoal(id: "Bush_IslandWest_15_3", num: 1, name: "Island West Bush", hint: "Follow coastline N past walnut door (15,3)"),
        WalnutGoal(id: "Buried_IslandWest_21_81", num: 1, name: "Island West Buried", hint: "In dark sand on SW coast, between circular indentations. (21,81)"),
        WalnutGoal(id: "Buried_IslandWest_62_76", num: 1, name: "Island West Buried", hint: "Among debris pile S of farm, between blue starfish (62,76)"),
        WalnutGoal(id: "Buried_IslandWest_39_24", num: 1, name: "Island West Buried", hint: "In Tiget Slime area, between tufts of long grass (39,24)"),
        WalnutGoal(id: "Buried_IslandWest_88_14", num: 1, name: "Island West Buried", hint: "In grass in NE corner, between animated tiles (88,14)"),
        WalnutGoal(id: "Buried_IslandWest_43_74", num: 1, name: "Island West Buried", hint: "Near tidal pools between blue and yellow starfish, initially blocked by boulder (43,74)"),
        WalnutGoal(id: "Buried_IslandWest_30_75", num: 1, name: "Island West Buried", hint: "Between tidal pools, marked by X (30,75)"),
        WalnutGoal(id: "IslandWestCavePuzzle", num: 3, name: "Island West Cave Puzzle", hint: "\"Simon Says\" musical crystals in hidden cave N of suspension bridge"),
        WalnutGoal(id: "SandDuggy", num: 1, name: "Island West Sand Duggy", hint: "Can place items to block other holes"),
        WalnutGoal(id: "TreeNutShot", num: 1, name: "Island North Palm Tree", hint: "Can use slingshot to knock walnut from tree"),
        WalnutGoal(id: "Mermaid", num: 5, name: "Island Cove Mermaid Puzzle", hint: "Use flute blocks to play Mermaids song; stones provide tuning clues"),
        WalnutGoal(id: "Buried_IslandSouthEastCave_36_26", num: 1, name: "Island Cove Cave Buried", hint: "Among the barrels across from the dock (36,26)"),
        WalnutGoal(id: "Buried_IslandSouthEast_25_17", num: 1, name: "Island Cove Buried", hint: "NE of star pool, between yellow starfish (25,17)"),
        WalnutGoal(id: "StardropPool", num: 1, name: "Island Cove Star Pool", hint: "Fish a walnut out of the pool"),
        WalnutGoal(id: "BananaShrine", num: 3, name: "Island Jungle Banana Shrine Reward", hint: "Place a banana on the shrine"),
        WalnutGoal(id: "IslandGourmand1", num: 5, name: "Island Farm Cave Gourmand Reward #1", hint: "Grow some melons for the Gourmand"),
        WalnutGoal(id: "IslandGourmand2", num: 5, name: "Island Farm Cave Gourmand Reward #2", hint: "Grow some wheat for the Gourmand"),
        WalnutGoal(id: "IslandGourmand3", num: 5, name: "Island Farm Cave Gourmand Reward #3", hint: "Grow some garlic for the Gourmand"),
        WalnutGoal(id: "IslandShrinePuzzle", num: 5, name: "Island Jungle Gem Shrine Reward", hint: "Place gems (amethyst, aquamarine, emerald, ruby, topaz) dropped by birds on appropriate pedestals"),
    ]

    static let extra: [WalnutGoal] = [
        WalnutGoal(id: "GoldenCoconut", num: 1, name: "Break a Golden Coconut", hint: ""),
    ]

    static let limited: [WalnutGoal] = [
        WalnutGoal(id: "Birdie", num: 5, name: "Birdie's Quest Reward", hint: ""),
        WalnutGoal(id: "Darts", num: 3, name: "Winning Darts Minigame", hint: ""),
        WalnutGoal(id: "TigerSlimeNut", num: 1, name: "Killing Island West Tiger Slimes", hint: ""),
        WalnutGoal(id: "VolcanoNormalChest", num: 1, name: "Looting Volcano Common Chests", hint: ""),
        WalnutGoal(id: "VolcanoRareChest", num: 1, name: "Looting Volcano Rare Chests", hint: ""),
        WalnutGoal(id: "VolcanoBarrel", num: 5, name: "Breaking Volcano \"Barrels\"", hint: ""),
        WalnutGoal(id: "VolcanoMining", num: 5, name: "Mining Stones in Volcano", hint: ""),
        WalnutGoal(id: "VolcanoMonsterDrop", num: 5, name: "Killing Monsters in Volcano", hint: ""),
        WalnutGoal(id: "IslandFarming", num: 5, name: "Harvesting Crops on Island Farm", hint: ""),
        WalnutGoal(id: "MusselStone", num: 5, name: "Breaking Shell Stones on Island Farm Beach", hint: ""),
        WalnutGoal(id: "IslandFishing", num: 5, name: "Fishing on the Island", hint: ""),
        WalnutGoal(id: "Island_N_BuriedTreasureNut", num: 1, name: "Journal Scrap #10 Buried Treasure", hint: "By curved tree just SW of Volcano entrance (27,28); must have read journal scrap"),
        WalnutGoal(id: "Island_W_BuriedTreasureNut", num: 1, name: "Journal Scrap #4 Buried Treasure", hint: "Between the bush clumps on beach N of Birdie's hut (18,42); must have read journal scrap"),
        WalnutGoal(id: "Island_W_BuriedTreasureNut2", num: 1, name: "Journal Scrap #6 Buried Treasure", hint: "Against wall on beach in SE corner of farm (104,74); must have read journal scrap"),
    ]

}
