import json, re, sys
sys.path.insert(0, '.')
from text import TRIG, ROLE
from eventmap import ids_for, hearts_of, OVERRIDE
OVERRIDE[("Leah","Six Hearts II")] = ["53|584059"]; OVERRIDE[("Leah","Eight Hearts")] = ["53|584059"]

SEASONS = ["Spring", "Summer", "Fall", "Winter"]
def fix(t):
    t = re.sub(r'\s+([.,;:)])', r'\1', t)
    t = re.sub(r"\s+'s\b", "'s", t)
    t = re.sub(r'\(\s+', '(', t)
    t = t.replace(' *', '*').replace('&amp;', '&')
    return t.strip()
def birthday(s):
    m = re.match(r'(\d+)\s+(\w+)', s) or re.match(r'(\w+)\s+(\d+)', s)
    a, b = m.group(1), m.group(2)
    return {'season': b, 'day': int(a)} if a.isdigit() else {'season': a, 'day': int(b)}
def family(lst):
    out = []
    for f in lst or []:
        m = re.match(r'(.+?)\s*\((.+)\)', fix(f))
        if m: out.append({'name': m.group(1).strip(), 'relation': m.group(2).strip()})
    return out
def marriage(s):
    s = s.lower()
    return 'roommate' if 'roommate' in s else ('yes' if s.startswith('yes') else 'no')
def tier(items):
    notes, names = [], []
    for it in items:
        it = fix(it)
        if it.startswith('All '): notes += [n.strip() for n in re.split(r'(?= All )', it) if n.strip()]
        else: names.append(it.rstrip('*').strip())
    return {'items': names, 'notes': notes}
chars = []
for d in json.load(open('npc.json')):
    n = d['name']
    sched = d['schedule']
    groups = []
    for s in sched['seasons']:
        conds = [{'title': fix(c['title']), 'rows': [[fix(r[0]), fix(r[1]).rstrip('.')] for r in c['rows']]} for c in s['conditions'] if c['rows']]
        if conds: groups.append({'title': fix(s['season']), 'conditions': conds})
    notes = [fix(p) for p in sched.get('intro', []) if not p.startswith('Shown below')]
    events = []
    for e in d['heartEvents']:
        if e['title'] == 'Anytime': continue
        raw = ' '.join(e['trigger'])
        is_mail = 'recipe in the mail' in raw and (n, e['title']) not in TRIG
        h = hearts_of(e['title'])
        if e['title'] == '50 Friendship Points': h = 0
        if e['title'] == 'Group Ten-Heart Event': h = 10
        events.append({
            'title': e['title'], 'hearts': h, 'isMail': is_mail, 'isGroup': e['title'] == 'Group Ten-Heart Event',
            'idKeys': [] if is_mail else ids_for(n, e['title']),
            'trigger': 'Sends you a cooking recipe in the mail.' if is_mail else TRIG[(n, e['title'])],
            'anchor': e['id'],
        })
    chars.append({
        'name': n, 'role': ROLE[n], 'birthday': birthday(d['birthday']),
        'livesIn': fix(d.get('livesIn', '')), 'address': fix(d.get('address', '')),
        'family': family(d.get('family')), 'marriage': marriage(d.get('marriage', 'No')),
        'clinic': fix(d.get('clinic', '')),
        'gifts': {k: tier(d['gifts'].get(k, [])) for k in ['love', 'like', 'neutral', 'dislike', 'hate']},
        'scheduleNotes': notes, 'schedule': groups, 'heartEvents': events,
    })
js = json.dumps(chars, ensure_ascii=False, separators=(',', ':'))
assert '"""#' not in js
out = f'''import Foundation

/// Villager reference data (birthdays, homes, gift tastes, schedules, heart-event triggers).
/// Facts compiled from the Stardew Valley Wiki (stardewvalleywiki.com, CC BY-NC-SA 3.0), October 2026;
/// schedule rows follow the wiki tables, all other prose is our own. Generated by Tools/characters/gen_swift.py.
enum CharacterData {{
    static let all: [CharacterInfo] = {{
        (try? JSONDecoder().decode([CharacterInfo].self, from: Data(json.utf8))) ?? []
    }}()

    static func info(for name: String) -> CharacterInfo? {{ all.first {{ $0.name == name }} }}

    static let json = #"""
{js}
"""#
}}
'''
open('/Users/pat/Projects/stardewvalley-checker/Sources/StardewCheckup/Parsing/CharacterData.swift', 'w').write(out)
print(len(js), 'bytes json;', len(chars), 'characters;', sum(len(c['heartEvents']) for c in chars), 'events;', sum(len(r['rows']) for c in chars for g in c['schedule'] for r in g['conditions']), 'schedule rows')
