# Our own wording for each character's role and heart-event triggers (facts from the wiki, text is ours).
ROLE = {
 "Abigail": "Pierre and Caroline's adventurous daughter; plays the flute by the mountain lake and loves anything spooky.",
 "Alex": "Lives with his grandparents at 1 River Road and dreams of playing pro gridball.",
 "Caroline": "Pierre's wife; runs the aerobics class and tends her sunroom garden behind the store.",
 "Clint": "The town blacksmith; upgrades tools and cracks geodes at his shop next to the river.",
 "Demetrius": "Robin's husband, a scientist who studies the valley's wildlife from the mountain house.",
 "Dwarf": "A mysterious trader living inside the Mines; you need the Dwarvish Translation Guide to talk to it.",
 "Elliott": "A writer living in a cabin on the beach while he works on his novel.",
 "Emily": "Haley's older sister; works evenings at the Saloon and makes her own clothes.",
 "Evelyn": "Alex's grandmother, 'Granny' to everyone; tends the town flower beds and bakes cookies.",
 "George": "Alex's grandfather, a grumpy retiree who watches TV at 1 River Road.",
 "Gus": "Owner and cook of the Stardrop Saloon.",
 "Haley": "Emily's younger sister, a photographer with an eye for fashion.",
 "Harvey": "The town doctor; runs the Medical Clinic and loves aviation and coffee.",
 "Jas": "Marnie's young niece and Shane's goddaughter; takes lessons with Penny.",
 "Jodi": "Sam and Vincent's mother; keeps house at 1 Willow Lane while Kent is away.",
 "Kent": "Jodi's husband, a soldier who returns to the valley at the start of Year 2.",
 "Krobus": "A friendly shadow creature who runs a shop in the Sewers and can move in as a roommate.",
 "Leah": "A sculptor living alone in a cottage in Cindersap Forest; forages for her meals.",
 "Leo": "A boy raised by parrots on Ginger Island who can later move to the valley.",
 "Lewis": "The mayor of Pelican Town; organizes every festival.",
 "Linus": "Lives off the land in a tent on the mountain and prefers it that way.",
 "Marnie": "Runs the animal ranch in Cindersap Forest and sells livestock.",
 "Maru": "Robin and Demetrius' daughter; tinkers with gadgets and works part-time at the clinic.",
 "Pam": "Penny's mother; drives the bus once it is repaired and spends evenings at the Saloon.",
 "Penny": "Pam's daughter; tutors Jas and Vincent and reads in the library.",
 "Pierre": "Owner of the general store; sells seeds and buys your produce.",
 "Robin": "The town carpenter; builds and upgrades farm buildings from the mountain shop.",
 "Sam": "Jodi's eldest son, a skateboarding musician who works at JojaMart.",
 "Sandy": "Runs the Oasis shop in the Calico Desert and is close friends with Emily.",
 "Sebastian": "Robin's son, a programmer who keeps to his basement room and rides a motorcycle.",
 "Shane": "Marnie's nephew; works at JojaMart and raises chickens behind the ranch.",
 "Vincent": "Jodi's youngest son; plays around town and takes lessons with Penny.",
 "Willy": "The old fisherman who runs the Fish Shop on the docks.",
 "Wizard": "Rasmodius, who lives in the tower in Cindersap Forest and studies the valley's magic.",
}
# key: (name, wiki heading) -> our trigger text
TRIG = {
 ("Abigail","Two Hearts"): "Go into Pierre's General Store while Abigail is inside, on any day but Saturday.",
 ("Abigail","Four Hearts"): "Be on the Mountain between noon and 7pm while it rains, in any season except Winter.",
 ("Abigail","Six Hearts"): "Walk into Pelican Town from any direction between 9pm and midnight on a dry day (leaving a shop or house in town counts).",
 ("Abigail","Eight Hearts"): "After her letter arrives, enter Pierre's store between 8pm and 10pm while she is there. The door locks at 9pm unless you have the Key To The Town; waiting in Caroline's sunroom and stepping into the kitchen also works.",
 ("Abigail","Ten Hearts"): "Enter the Mines or the Quarry Mine (or climb up from a lower floor) between 5pm and midnight. Does not fire once you have given her the Mermaid's Pendant.",
 ("Abigail","Group Ten-Heart Event"): "Unmarried, with a bouquet given to every bachelorette, all of them at 10 hearts and every 10-heart scene watched: enter Haley and Emily's house.",
 ("Abigail","Fourteen Hearts"): "Walk into the Backwoods between 6:10am and 5pm.",
 ("Alex","Two Hearts"): "Go to the Beach on a sunny Summer day while Alex is there.",
 ("Alex","Four Hearts"): "Enter Pelican Town between 9am and 4pm.",
 ("Alex","Five Hearts"): "Enter Alex's house while he is home.",
 ("Alex","Six Hearts"): "Enter Alex's house while he is home.",
 ("Alex","Eight Hearts"): "Go to the Beach on a sunny day while Alex is there (normally Summer only, though he can pass through on the way to the Ginger Island resort once it is open).",
 ("Alex","Ten Hearts"): "He mails you an invitation to the Saloon; afterwards enter the Saloon between 7pm and 10pm.",
 ("Alex","Group Ten-Heart Event"): "Unmarried, with a bouquet given to every bachelor, all of them at 10 hearts and every 10-heart scene watched: enter the Stardrop Saloon.",
 ("Alex","Fourteen Hearts"): "In Year 2 or later, leave the farmhouse between 6am and 8:20am on any day except Sunday with at least 5,000g on hand.",
 ("Caroline","Two Hearts"): "Step into the sunroom through the door in Caroline's kitchen between 9am and 5pm on a dry day.",
 ("Caroline","Six Hearts"): "Enter Pierre's General Store while both Caroline and Abigail are inside.",
 ("Clint","Three Hearts I"): "Go to the Saloon on a Monday between 7pm and 11pm.",
 ("Clint","Six Hearts"): "Walk into town from Cindersap Forest between 9am and 6:30pm after seeing his first 3-heart scene. Blocked if you married Emily or have seen her 8- or 10-heart event.",
 ("Demetrius","Six Hearts"): "Enter the mountain house while Demetrius and Robin are both inside.",
 ("Dwarf","50 Friendship Points"): "With at least 50 friendship points, enter the Sewers after buying the Stardrop from Krobus.",
 ("Elliott","Two Hearts"): "Enter Elliott's cabin while he is home.",
 ("Elliott","Four Hearts"): "Enter the Stardrop Saloon between 3pm and 10pm while Gus is there.",
 ("Elliott","Six Hearts"): "Enter Elliott's cabin while he is home.",
 ("Elliott","Eight Hearts"): "After his letter arrives, visit the Museum between 1pm and 7pm (any later day is fine).",
 ("Elliott","Ten Hearts"): "Go to the Beach on a dry day between 7am and 1pm. He sends a letter, but it is not required.",
 ("Elliott","Group Ten-Heart Event"): "Unmarried, with a bouquet given to every bachelor, all of them at 10 hearts and every 10-heart scene watched: enter the Stardrop Saloon.",
 ("Elliott","Fourteen Hearts"): "Leave the farmhouse or enter the Farm while Elliott is outside on it, between 6am and 3pm, with no festival in the next 8 days.",
 ("Emily","Two Hearts"): "Enter Emily's house while she is home.",
 ("Emily","Four Hearts"): "Enter Pelican Town on a sunny day, any season but Winter.",
 ("Emily","Six Hearts"): "Enter Emily's house while she is home.",
 ("Emily","Eight Hearts"): "A letter invites you to the Mayor's Manor during opening hours; later days also work. Requires her 6-heart event first.",
 ("Emily","Ten Hearts"): "A letter asks you to meet her in the Secret Woods after 10pm on a dry, non-festival night. You need a Steel Axe to clear the log; the scene ends the day.",
 ("Emily","Group Ten-Heart Event"): "Unmarried, with a bouquet given to every bachelorette, all of them at 10 hearts and every 10-heart scene watched: enter Haley and Emily's house.",
 ("Emily","Fourteen Hearts"): "Leave the farmhouse between 6am and 8:20am.",
 ("Evelyn","Four Hearts"): "Enter Evelyn's house while she is inside.",
 ("George","Six Hearts"): "Enter George's house while he is home.",
 ("Gus","Four Hearts"): "Enter the Saloon during opening hours while Gus is inside. Needs at least 2 hearts with Pam.",
 ("Gus","Five Hearts"): "Leave the farmhouse on a dry day between 6am and 11:30am.",
 ("Haley","Two Hearts"): "Enter Haley and Emily's house while both sisters are home.",
 ("Haley","Four Hearts"): "Enter Haley's house while she is home.",
 ("Haley","Six Hearts"): "Go to the Beach between 10am and 4pm in any season except Winter.",
 ("Haley","Eight Hearts"): "Enter Cindersap Forest between 10am and 4pm on a sunny day, any season but Winter.",
 ("Haley","Ten Hearts"): "Enter Haley's house while she is home.",
 ("Haley","Group Ten-Heart Event"): "Unmarried, with a bouquet given to every bachelorette, all of them at 10 hearts and every 10-heart scene watched: enter Haley and Emily's house (plays together with her own 10-heart scene).",
 ("Haley","Fourteen Hearts"): "Part 1: enter town between 8am and 3pm on a dry day. Part 2, a day or more later: enter the farmhouse between 6:20am and 5pm. Part 3, a day or more later: enter town between 6am and 3pm on a dry day carrying a Chocolate Cake.",
 ("Harvey","Two Hearts"): "Enter George's house while George is there.",
 ("Harvey","Four Hearts"): "Enter the Clinic while Harvey is there.",
 ("Harvey","Six Hearts"): "Enter Pierre's General Store between 11am and 3pm.",
 ("Harvey","Eight Hearts"): "Enter the Clinic.",
 ("Harvey","Ten Hearts"): "He mails you asking to meet at the Railroad; go there between 9am and 5pm.",
 ("Harvey","Group Ten-Heart Event"): "Unmarried, with a bouquet given to every bachelor, all of them at 10 hearts and every 10-heart scene watched: enter the Stardrop Saloon.",
 ("Harvey","Fourteen Hearts"): "Enter a farmhouse upgraded at least twice between 8pm and midnight.",
 ("Jas","Eight Hearts"): "With 8 hearts with both Jas and Vincent, enter Cindersap Forest on a sunny Spring day between 6am and 5pm.",
 ("Jodi","Two Hearts"): "Once at 2 hearts you can enter her bedroom and read Kent's letter in the drawer by her bed.",
 ("Jodi","Four Hearts"): "Leave the farmhouse on a Monday between 6am and 9:30am; Jodi is waiting outside.",
 ("Kent","Three Hearts I"): "Enter Kent's house while he and Jodi are both home.",
 ("Krobus","Fourteen Hearts"): "Enter the Beach between 8pm and 1am on a dry night.",
 ("Leah","Two Hearts"): "Enter Leah's Cottage while she is home.",
 ("Leah","Four Hearts"): "Enter Leah's Cottage while she is home.",
 ("Leah","Six Hearts I"): "Leah knocks at the farmhouse between 6am and 11:30am on a dry day.",
 ("Leah","Six Hearts II"): "Enter Cindersap Forest while Leah is there, any season except Winter.",
 ("Leah","Eight Hearts"): "If you suggested the art show at 2 hearts: Leah comes to the farmhouse between 6am and 8am (not in Winter) to invite you; then enter town between 3pm and 5pm on any later day.",
 ("Leah","Ten Hearts"): "Enter Cindersap Forest between 11am and 4pm on a sunny day, any season except Winter.",
 ("Leah","Group Ten-Heart Event"): "Unmarried, with a bouquet given to every bachelorette, all of them at 10 hearts and every 10-heart scene watched: enter Haley and Emily's house.",
 ("Leah","Fourteen Hearts"): "Leave the farmhouse between 6am and 8:20am on a sunny day that is not a Sunday and not in Winter.",
 ("Leo","Two Hearts"): "Enter Island West on a sunny day between 6am and 6pm.",
 ("Leo","Four Hearts"): "Enter Island North on a sunny day between 6am and 6pm, before Leo moves to the valley.",
 ("Leo","Six Hearts"): "Enter Island South on a sunny day between 6am and 6pm.",
 ("Leo","Nine Hearts"): "Enter the Mountain on a dry day between 6am and 7pm.",
 ("Lewis","Six Hearts"): "Enter town on a sunny day between 7pm and 11pm. Marnie must also be at 6 hearts.",
 ("Linus","Zero Hearts"): "With 50+ friendship points, enter town between 8pm and midnight on a dry night (not before Spring 7 of Year 1).",
 ("Linus","Four Hearts"): "Enter the mountain area by his tent between 8pm and midnight on a dry night.",
 ("Linus","Eight Hearts"): "Leave Robin's house on a dry day between 9am and 5pm.",
 ("Marnie","Three Hearts I"): "Leave the farmhouse between 6am and 9:30am.",
 ("Marnie","Six Hearts"): "Enter town on a sunny day between 7pm and 11pm. Lewis must also be at 6 hearts.",
 ("Maru","Two Hearts"): "Enter the Carpenter's Shop while Maru is there.",
 ("Maru","Four Hearts"): "Enter the Clinic while Maru is there.",
 ("Maru","Six Hearts"): "Enter the Mountain on a sunny night between 9pm and 11:40pm.",
 ("Maru","Eight Hearts"): "Enter the Carpenter's Shop while Maru is there.",
 ("Maru","Ten Hearts"): "Enter the Carpenter's Shop between 9am and 4pm.",
 ("Maru","Group Ten-Heart Event"): "Unmarried, with a bouquet given to every bachelorette, all of them at 10 hearts and every 10-heart scene watched: enter Haley and Emily's house.",
 ("Maru","Fourteen Hearts"): "Part 1: enter the farmhouse between 6:10am and 5pm on a non-Sunday outside Winter. Part 2: enter the Mountain between 10pm and 1am on a clear night.",
 ("Pam","Nine Hearts"): "Buy the Community Upgrade from Robin; with 9 hearts, enter Pam's new house at least 4 days after it is finished.",
 ("Penny","Two Hearts"): "Enter Pelican Town on a sunny day between 9am and 2pm.",
 ("Penny","Four Hearts"): "Enter the trailer while Penny is home.",
 ("Penny","Six Hearts"): "Enter the trailer while Penny is home.",
 ("Penny","Eight Hearts"): "Enter Cindersap Forest on a sunny day between 9am and 4pm.",
 ("Penny","Ten Hearts"): "After her letter arrives, enter the pool area of the Spa between 7pm and midnight.",
 ("Penny","Group Ten-Heart Event"): "Unmarried, with a bouquet given to every bachelorette, all of them at 10 hearts and every 10-heart scene watched: enter Haley and Emily's house.",
 ("Penny","Fourteen Hearts"): "Enter the farmhouse between 3pm and 7pm while she is home.",
 ("Pierre","Six Hearts"): "Enter Pierre's General Store.",
 ("Robin","Six Hearts"): "Enter Robin's house while she is home.",
 ("Sam","Two Hearts"): "Enter Sam's house while he is home.",
 ("Sam","Three Hearts"): "Year 1 only: enter the Beach on a sunny day between 7am and 3pm, any season except Winter.",
 ("Sam","Four Hearts"): "Enter Sam's house while he is home.",
 ("Sam","Six Hearts"): "Enter town between noon and 4pm on a dry day.",
 ("Sam","Eight Hearts"): "Sam shows up at your door between 6am and 8am; requires his 2-heart event.",
 ("Sam","Ten Hearts"): "After his letter arrives, enter town on a clear night between 8pm and midnight.",
 ("Sam","Group Ten-Heart Event"): "Unmarried, with a bouquet given to every bachelor, all of them at 10 hearts and every 10-heart scene watched: enter the Stardrop Saloon.",
 ("Sam","Fourteen Hearts"): "Four parts: enter a twice-upgraded farmhouse between 6:10am and 5pm while Sam is inside, then again 3 days later, 3 days after that, and 4 days after that.",
 ("Sebastian","Two Hearts"): "Enter Sebastian's room while he is there.",
 ("Sebastian","Four Hearts"): "Go to the Mountain between 11am and 5pm.",
 ("Sebastian","Six Hearts"): "Enter Sebastian's room while he is there.",
 ("Sebastian","Eight Hearts"): "Go to the Beach on a rainy day between noon and 11pm.",
 ("Sebastian","Ten Hearts"): "Go to the Mountain between 8pm and midnight.",
 ("Sebastian","Group Ten-Heart Event"): "Unmarried, with a bouquet given to every bachelor, all of them at 10 hearts and every 10-heart scene watched: enter the Stardrop Saloon.",
 ("Sebastian","Fourteen Hearts"): "Go to the Mountain on a rainy day between 6am and 7pm.",
 ("Shane","Two Hearts"): "Enter Cindersap Forest between 8pm and midnight.",
 ("Shane","Four Hearts"): "Enter Marnie's Ranch at any time (his dialogue also warms up at this level).",
 ("Shane","Six Hearts"): "Enter Cindersap Forest between 9am and 8pm while it is raining or storming.",
 ("Shane","Seven Hearts I"): "After his 6-heart scene, enter Marnie's Ranch while Shane is home.",
 ("Shane","Seven Hearts II"): "Enter town between 10am and 4pm on a sunny day, with at least 2 hearts with both Emily and Clint.",
 ("Shane","Eight Hearts"): "Enter Marnie's Ranch while Shane is home, after the follow-up visit that comes after his 6-heart scene.",
 ("Shane","Ten Hearts"): "Leave the farmhouse before 6:30am to start it, then be at the Bus Stop between 4pm and 6pm.",
 ("Shane","Group Ten-Heart Event"): "Unmarried, with a bouquet given to every bachelor, all of them at 10 hearts and every 10-heart scene watched: enter the Stardrop Saloon.",
 ("Shane","Fourteen Hearts"): "Enter town between 8am and 5pm on any day but Friday; parts 2 and 3 play when you enter town on each of the next two days.",
 ("Vincent","Eight Hearts"): "With 8 hearts with both Vincent and Jas, enter Cindersap Forest on a sunny Spring day between 6am and 5pm.",
 ("Willy","Six Hearts"): "Enter the Beach between 6am and 5:10pm.",
 ("Wizard","Four Hearts"): "Not a cutscene: the tower basement opens, where the Shrine of Illusions lets you change your appearance for 500g.",
}
